"""empty message

Revision ID: 1847bdd36b31
Revises: 9a52760ac110
Create Date: 2021-10-09 10:12:53.874298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1847bdd36b31"
down_revision = "9a52760ac110"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
