"""Add new fields to user model

Revision ID: 9a52760ac110
Revises: 4e7b5453c958
Create Date: 2021-10-08 20:40:16.280592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a52760ac110"
down_revision = "4e7b5453c958"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("about_me", sa.String(length=140), nullable=True)
    )
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
